### ISSUE TITLE
Crash after starting it using systemd on sleep

### ISSUE THREAD

**Issue by nemanjan00** [meskarune/i3lock-fancy#132]
This is the result of systemd status: 
```
 ✘ nemanjan00@nemanjan00-laptop  ~   master  systemctl status wakelock.service 
● wakelock.service - Lock the screen on resume from suspend
   Loaded: loaded (/etc/systemd/system/wakelock.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Thu 2018-08-09 08:54:24 CEST; 12min ago
  Process: 12972 ExecStart=/home/nemanjan00/lock.sh (code=exited, status=1/FAILURE)

Aug 09 08:54:24 nemanjan00-laptop lock.sh[12972]: Direct leak of 144 byte(s) in 6 object(s) allocated from:
Aug 09 08:54:24 nemanjan00-laptop lock.sh[12972]:     #0 0x7f33573bd019 in __interceptor_malloc /build/gcc/src/gcc/libsanitizer/asan/asan_malloc_linux.cc:86
Aug 09 08:54:24 nemanjan00-laptop lock.sh[12972]:     #1 0x7f335586ad7e in FcPatternCreate (/usr/lib/libfontconfig.so.1+0x1ed7e)
Aug 09 08:54:24 nemanjan00-laptop lock.sh[12972]: Indirect leak of 192 byte(s) in 6 object(s) allocated from:
Aug 09 08:54:24 nemanjan00-laptop lock.sh[12972]:     #0 0x7f33573bd231 in __interceptor_calloc /build/gcc/src/gcc/libsanitizer/asan/asan_malloc_linux.cc:95
Aug 09 08:54:24 nemanjan00-laptop lock.sh[12972]:     #1 0x7f335586bdd9  (/usr/lib/libfontconfig.so.1+0x1fdd9)
Aug 09 08:54:24 nemanjan00-laptop lock.sh[12972]: SUMMARY: AddressSanitizer: 1872 byte(s) leaked in 18 allocation(s).
Aug 09 08:54:24 nemanjan00-laptop systemd[1]: wakelock.service: Control process exited, code=exited status=1
Aug 09 08:54:24 nemanjan00-laptop systemd[1]: wakelock.service: Failed with result 'exit-code'.
Aug 09 08:54:24 nemanjan00-laptop systemd[1]: Failed to start Lock the screen on resume from suspend.
```

This is the content of daemon: 

```
[Unit]
Description=Lock the screen on resume from suspend

[Service]
User=nemanjan00
Type=forking
Environment=DISPLAY=:0
ExecStart=/home/nemanjan00/lock.sh

[Install]
WantedBy=sleep.target
WantedBy=suspend.target
```

And this is the lock.sh: 

```
#!/bin/sh

B='#00000000'  # blank
C='#ffffff22'  # clear ish
D='#ff00ffcc'  # default
T='#ee00eeee'  # text
W='#880000bb'  # wrong
V='#bb00bbbb'  # verifying

/usr/bin/i3lock \
--insidevercolor=$C   \
--ringvercolor=$V     \
\
--insidewrongcolor=$C \
--ringwrongcolor=$W   \
\
--insidecolor=$B      \
--ringcolor=$D        \
--linecolor=$B        \
--separatorcolor=$D   \
\
--verifcolor=$T        \
--wrongcolor=$T        \
--timecolor=$T        \
--datecolor=$T        \
--layoutcolor=$T      \
--keyhlcolor=$W       \
--bshlcolor=$W        \
\
--screen 1            \
--blur 5              \
--clock               \
--indicator           \
--timestr="%H:%M:%S"  \
--datestr="%A, %m %Y" \
--keylayout 2         \
# --veriftext="Drinking verification can..."
# --wrongtext="Nope!"
# --textsize=20
# --modsize=10
# --timefont=comic-sans
# --datefont=monofur
# etc
```

When I close the lid and open it again, there is lockscreen for half of the second, and, then, it just dissapears...

**Comment by meskarune** [comment]
This is an issue with the upstream i3lock-color. However I believe the problem is in the i3lock-color build and if you use the old dev build you will end up with that error. The fix is to use the latest version from git. If you are on Arch Linux install i3lock-color-git instead.

**Comment by nemanjan00** [comment]
Thanks a lot! :)
