### ISSUE TITLE
Memory leak in Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by htr3n** [meskarune/i3lock-fancy#162]
Similar to the error that I reported on `i3lock-fancy-rapid` here: https://github.com/yvbbrjdr/i3lock-fancy-rapid/issues/12. I cross-link hoping that there might be the same root cause.

```sh
$ i3lock-fancy -gpf Ubuntu -- scrot -z 

=================================================================
==44737==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 4864 byte(s) in 19 object(s) allocated from:
    #0 0x7fe8ca835bc8 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x10dbc8)
    #1 0x7fe8c9aaa2f4  (/usr/lib/x86_64-linux-gnu/libfontconfig.so.1+0x212f4)

Indirect leak of 1184 byte(s) in 37 object(s) allocated from:
    #0 0x7fe8ca835dc6 in calloc (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x10ddc6)
    #1 0x7fe8c9aaa93c  (/usr/lib/x86_64-linux-gnu/libfontconfig.so.1+0x2193c)

Indirect leak of 341 byte(s) in 34 object(s) allocated from:
    #0 0x7fe8ca7be3dd in strdup (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x963dd)
    #1 0x7fe8c9aa9b64 in FcValueSave (/usr/lib/x86_64-linux-gnu/libfontconfig.so.1+0x20b64)

SUMMARY: AddressSanitizer: 6389 byte(s) leaked in 90 allocation(s).
```

Running `i3lock-fancy`, it took a while but then successfully locked the screen. After unlocking with password, the error above was shown.

My OS is Ubuntu 20.04 LTS.

**Comment by htr3n** [comment]
Similar to this one too: https://github.com/Raymo111/i3lock-color/issues/88

**Comment by htr3n** [comment]
Finally, upgrade i3lock (from github master) resolved the error. See: https://github.com/i3/i3lock/issues/167

**Comment by htr3n** [comment]
Related to this bug: https://github.com/i3/i3lock/issues/167

**Comment by AladW** [comment]
Upstream issue.
